apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-api
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: git@github.com:MaxymLy/mlflow-inference-api.git
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
